AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Datadog lambda monitor example

Parameters:

  Env:
    Type: String
    Description: Environment
    Default: dev
  Secrets:
    Type: String
    Description: The name of the secrets in AWS SM.
    Default: 'dev/CloudFormation/DataDogKeys'

Resources:

  DataDogMonitorLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: datadog_lambda_function.handler
      Runtime: python3.6
      Description: A function which manages the creation of monitors in DataDog.
      Tracing: Active
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Secrets}*'
      Environment:
        Variables:
          SECRETS: !Ref Secrets 

  TestLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.handler
      Runtime: python3.6
      Description: A test function.
      Tracing: Active
      Tags:
        env: !Ref Env
      
  TestLambdaDDMonitor:
    Type: 'Custom::DataDogMonitor'
    Properties: 
      ServiceToken: !GetAtt DataDogMonitorLambda.Arn
      Name: "CR TestLambda Monitor"
      FunctionName: !Ref TestLambda
      Message: "Test Message \n@harry.daniels@email.co.uk"
      Priority: 3
      Tags: 
        - "env:dev"
